import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { supabase } from "./supabase.js";
import DriveFiles from "./DriveFiles.jsx";
import KPIDashboard from "./KPIDashboard.jsx";
import Approvals from "./Approvals.jsx";
import ContentCalendar from "./ContentCalendar.jsx";
import Pipeline from "./Pipeline.jsx";
import generateQBR from "./QBRReport.jsx";

const STATUS_OPTS=[{value:"briefing",label:"Briefing",color:"#6B7280",icon:"📋"},{value:"en_progreso",label:"En Progreso",color:"#F59E0B",icon:"⚡"},{value:"revision",label:"En Revisión",color:"#8B5CF6",icon:"🔍"},{value:"aprobado",label:"Aprobado",color:"#10B981",icon:"✅"},{value:"entregado",label:"Entregado",color:"#3B82F6",icon:"📦"}];
const DEL_TYPES=[{value:"imagen",label:"Imagen",icon:"🖼️"},{value:"video",label:"Video",icon:"🎬"},{value:"manual_marca",label:"Manual de Marca",icon:"📖"},{value:"presentacion",label:"Presentación",icon:"📊"},{value:"documento",label:"Documento",icon:"📄"},{value:"otro",label:"Otro",icon:"📎"}];
const PROSP_TYPES=[{value:"propuesta_visual",label:"Propuesta Visual",icon:"🎨"},{value:"propuesta_economica",label:"Propuesta Económica",icon:"💰"},{value:"pagina_web",label:"Página Web",icon:"🌐"},{value:"otro",label:"Otro",icon:"📎"}];
const PRIOS=[{value:"baja",label:"Baja",color:"#6B7280"},{value:"media",label:"Media",color:"#F59E0B"},{value:"alta",label:"Alta",color:"#EF4444"},{value:"urgente",label:"Urgente",color:"#DC2626"}];
const TSTAT=[{value:"pendiente",label:"Pendiente",color:"#6B7280"},{value:"en_progreso",label:"En Progreso",color:"#F59E0B"},{value:"completado",label:"Completado",color:"#10B981"}];
const CATS=[{value:"cliente",label:"Cliente",color:"#60A5FA",icon:"💼"},{value:"propuesta",label:"Propuesta",color:"#F59E0B",icon:"📄"},{value:"interno",label:"Interno",color:"#A78BFA",icon:"🏠"}];
const PROJ_TYPES=[{value:"",label:"— Sin tipo —"},{value:"propuesta_visual",label:"Propuesta Visual"},{value:"website",label:"Website"},{value:"branding",label:"Branding"},{value:"catalogo",label:"Catálogo"},{value:"social_media",label:"Social Media"},{value:"video",label:"Video/Producción"},{value:"otro",label:"Otro"}];
const todayStr=()=>new Date().toISOString().split("T")[0];
const F="'DM Sans',sans-serif",D="'Sora',sans-serif";
const C={bg:"#08080A",s:"#111115",s2:"#18181E",b:"#222230",tx:"#F0F0F4",tm:"#9898A8",td:"#5A5A6E",acc:"#CDFF50",accD:"#A8D93A",r:"#FF4D6A",rBg:"#1A0810",g:"#34D399",w:"#FBBF24",p:"#A78BFA",pBg:"#120E1A",bl:"#60A5FA",blBg:"#0A1220"};
const CSS=`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Sora:wght@400;500;600;700;800&display=swap');@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}@keyframes modalIn{from{opacity:0;transform:scale(.96)}to{opacity:1;transform:scale(1)}}*{box-sizing:border-box;margin:0;padding:0}body{font-family:${F};background:${C.bg};color:${C.tx}}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:${C.b};border-radius:3px}select option{background:${C.s};color:${C.tx}}`;
function extractFolderId(u){if(!u)return null;const m=u.match(/folders\/([a-zA-Z0-9_-]+)/);return m?m[1]:(/^[a-zA-Z0-9_-]{20,}$/.test(u)?u:null)}

function Ic({n,sz=18}){const d={dash:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,prosp:<><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></>,cli:<><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8"/><path d="M12 17v4"/></>,usr:<><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></>,emp:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" y1="8" x2="19" y2="14"/><line x1="22" y1="11" x2="16" y2="11"/></>,cal:<><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></>,out:<><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16,17 21,12 16,7"/><line x1="21" y1="12" x2="9" y2="12"/></>,plus:<><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></>,file:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/></>,dl:<><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7,10 12,15 17,10"/><line x1="12" y1="15" x2="12" y2="3"/></>,tr:<><polyline points="3,6 5,6 21,6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></>,back:<><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12,19 5,12 12,5"/></>,srch:<><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></>,lock:<><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></>,check:<><polyline points="20,6 9,17 4,12"/></>,todo:<><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></>,edit:<><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></>,sync:<><path d="M21 2v6h-6"/><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M3 22v-6h6"/><path d="M21 12a9 9 0 0 1-15 6.7L3 16"/></>,pipe:<><line x1="6" y1="3" x2="6" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M18 9a9 9 0 0 1-9 9"/></>,link:<><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></>};return<svg width={sz} height={sz} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{d[n]}</svg>}

function Btn({children,onClick,v="primary",sz="md",icon,disabled,style:sx}){const b={display:"inline-flex",alignItems:"center",gap:6,border:"none",cursor:disabled?"not-allowed":"pointer",fontFamily:F,fontWeight:600,borderRadius:8,transition:"all .15s",opacity:disabled?.4:1,whiteSpace:"nowrap",fontSize:sz==="sm"?11:sz==="lg"?14:12,padding:sz==="sm"?"5px 10px":sz==="lg"?"12px 24px":"7px 14px"};const vs={primary:{background:C.acc,color:"#0A0A0B"},secondary:{background:C.s2,color:C.tx,border:`1px solid ${C.b}`},danger:{background:C.rBg,color:C.r,border:"1px solid #3D1525"},ghost:{background:"transparent",color:C.tm}};return<button onClick={onClick} disabled={disabled} style={{...b,...vs[v],...sx}}>{icon&&<Ic n={icon} sz={sz==="sm"?13:15}/>}{children}</button>}
function Inp({label,...p}){return<div style={{display:"flex",flexDirection:"column",gap:5}}>{label&&<label style={{fontSize:11,fontWeight:600,color:C.tm,fontFamily:F,textTransform:"uppercase",letterSpacing:".06em"}}>{label}</label>}<input {...p} style={{background:C.bg,border:`1px solid ${C.b}`,borderRadius:8,padding:"9px 12px",color:C.tx,fontSize:13,fontFamily:F,outline:"none",width:"100%",...p.style}} onFocus={e=>e.target.style.borderColor=C.acc} onBlur={e=>e.target.style.borderColor=C.b}/></div>}
function Sel({label,options,...p}){return<div style={{display:"flex",flexDirection:"column",gap:5}}>{label&&<label style={{fontSize:11,fontWeight:600,color:C.tm,fontFamily:F,textTransform:"uppercase",letterSpacing:".06em"}}>{label}</label>}<select {...p} style={{background:C.bg,border:`1px solid ${C.b}`,borderRadius:8,padding:"9px 12px",color:C.tx,fontSize:13,fontFamily:F,outline:"none",cursor:"pointer",...p.style}}>{options.map(o=><option key={o.value} value={o.value}>{o.label||o.value}</option>)}</select></div>}
function Txt({label,...p}){return<div style={{display:"flex",flexDirection:"column",gap:5}}>{label&&<label style={{fontSize:11,fontWeight:600,color:C.tm,fontFamily:F,textTransform:"uppercase",letterSpacing:".06em"}}>{label}</label>}<textarea {...p} style={{background:C.bg,border:`1px solid ${C.b}`,borderRadius:8,padding:"9px 12px",color:C.tx,fontSize:13,fontFamily:F,outline:"none",resize:"vertical",minHeight:70,width:"100%",...p.style}} onFocus={e=>e.target.style.borderColor=C.acc} onBlur={e=>e.target.style.borderColor=C.b}/></div>}
function Mod({title,onClose,children,w=520}){return<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,backdropFilter:"blur(8px)"}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div style={{background:C.s,borderRadius:16,border:`1px solid ${C.b}`,width:"92%",maxWidth:w,maxHeight:"88vh",overflow:"auto",animation:"modalIn .2s ease"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",borderBottom:`1px solid ${C.b}`,position:"sticky",top:0,background:C.s,zIndex:1}}><h3 style={{fontFamily:D,fontSize:16,fontWeight:600,color:C.tx}}>{title}</h3><button onClick={onClose} style={{background:"none",border:"none",color:C.tm,cursor:"pointer",fontSize:18}}>✕</button></div><div style={{padding:20}}>{children}</div></div></div>}
function Badge({label,color}){return<span style={{display:"inline-flex",alignItems:"center",gap:4,padding:"3px 9px",borderRadius:20,fontSize:10,fontWeight:700,background:color+"18",color,fontFamily:F}}>{label}</span>}
function SBadge({status}){const s=STATUS_OPTS.find(o=>o.value===status)||STATUS_OPTS[0];return<Badge label={`${s.icon} ${s.label}`} color={s.color}/>}
function CatBadge({cat}){const c=CATS.find(x=>x.value===cat)||CATS[0];return<Badge label={`${c.icon} ${c.label}`} color={c.color}/>}
function Empty({icon,title,sub}){return<div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"48px 20px",textAlign:"center"}}><div style={{fontSize:40,marginBottom:12,opacity:.4}}>{icon}</div><div style={{fontFamily:D,fontSize:15,fontWeight:600,color:C.tm,marginBottom:4}}>{title}</div><div style={{fontSize:12,color:C.td,maxWidth:280}}>{sub}</div></div>}
function Stat({label,value,icon,color}){return<div style={{background:C.s,borderRadius:14,border:`1px solid ${C.b}`,padding:"18px 20px",flex:"1 1 160px",minWidth:150}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><span style={{fontSize:10,fontWeight:700,color:C.tm,textTransform:"uppercase",letterSpacing:".08em"}}>{label}</span><span style={{fontSize:18}}>{icon}</span></div><div style={{fontFamily:D,fontSize:28,fontWeight:800,color:color||C.tx}}>{value}</div></div>}
function Card({children,style:sx,onClick,hover}){const r=useRef(null);return<div ref={r} onClick={onClick} style={{background:C.s,borderRadius:14,border:`1px solid ${C.b}`,padding:18,cursor:onClick?"pointer":"default",transition:"all .15s",...sx}} onMouseEnter={()=>{if(hover&&r.current){r.current.style.borderColor=C.acc+"40";r.current.style.transform="translateY(-2px)"}}} onMouseLeave={()=>{if(hover&&r.current){r.current.style.borderColor=C.b;r.current.style.transform=""}}}>{children}</div>}
function FileCard({file,onDelete,showDel=true}){const info=[...DEL_TYPES,...PROSP_TYPES].find(x=>x.value===file.file_type)||{icon:"📎",label:"Archivo"};const handleDL=async()=>{if(file.url){window.open(file.url,"_blank");return}if(file.storage_path){const{data}=supabase.storage.from("wauya-files").getPublicUrl(file.storage_path);if(data?.publicUrl)window.open(data.publicUrl,"_blank")}};return<div style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",background:C.bg,borderRadius:10,border:`1px solid ${C.b}`}}><span style={{fontSize:20,flexShrink:0}}>{info.icon}</span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:600,color:C.tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{file.name}</div><div style={{fontSize:10,color:C.td}}>{info.label} · {file.size||"—"}</div></div><div style={{display:"flex",gap:4,flexShrink:0}}><button onClick={handleDL} style={{background:C.blBg,border:`1px solid ${C.bl}30`,cursor:"pointer",color:C.bl,padding:"5px 10px",borderRadius:6,display:"flex",alignItems:"center",gap:4,fontSize:10,fontFamily:F,fontWeight:600}}><Ic n="dl" sz={13}/>Descargar</button>{showDel&&onDelete&&<button onClick={()=>onDelete(file.id)} style={{background:"none",border:"none",cursor:"pointer",color:C.r,padding:4}}><Ic n="tr" sz={14}/></button>}</div></div>}
function MiniBar({data,height=130}){const max=Math.max(...data.map(d=>d.value),1);return<div style={{display:"flex",alignItems:"flex-end",gap:8,height,padding:"0 4px"}}>{data.map((d,i)=><div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><span style={{fontSize:11,fontWeight:700,color:C.tx}}>{d.value}</span><div style={{width:"100%",maxWidth:44,height:`${(d.value/max)*(height-40)}px`,minHeight:4,background:`linear-gradient(180deg,${d.color},${d.color}88)`,borderRadius:"5px 5px 2px 2px",transition:"height .4s"}}/><span style={{fontSize:9,color:C.td,textAlign:"center",lineHeight:1.2}}>{d.label}</span></div>)}</div>}
function Donut({data,size=110}){const total=data.reduce((a,d)=>a+d.value,0)||1;let cum=0;const r=size/2-10,cx=size/2,cy=size/2;return<svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>{data.filter(d=>d.value>0).map((d,i)=>{const s0=cum/total*360;cum+=d.value;const e0=cum/total*360;const g=2,s=(s0+g/2)*Math.PI/180,e=(e0-g/2)*Math.PI/180;if(e0-s0<1)return null;const la=e0-s0>180?1:0;const path=`M ${cx+r*Math.cos(s)} ${cy+r*Math.sin(s)} A ${r} ${r} 0 ${la} 1 ${cx+r*Math.cos(e)} ${cy+r*Math.sin(e)}`;return<path key={i} d={path} fill="none" stroke={d.color} strokeWidth={12} strokeLinecap="round"/>})}<text x={cx} y={cy-3} textAnchor="middle" fill={C.tx} fontFamily={D} fontWeight="800" fontSize="18">{total}</text><text x={cx} y={cy+11} textAnchor="middle" fill={C.td} fontFamily={F} fontSize="8">TOTAL</text></svg>}

// ─── TASK ROW (shared between views) ───
function TaskRow({td,employees,onStatusChange,onEdit,onDelete,showProject=false,clients,prospects}){
  const emp=employees.find(e=>e.id===td.assigned_to);const pr=PRIOS.find(p=>p.value===td.priority);const st=TSTAT.find(s=>s.value===td.status);const cat=CATS.find(c=>c.value===(td.category||"cliente"))||CATS[0];
  const projName=td.client_id?clients?.find(x=>x.id===td.client_id)?.company:td.prospect_id?prospects?.find(x=>x.id===td.prospect_id)?.company:"Interno";
  return<div style={{display:"flex",alignItems:"center",gap:8,padding:"9px 12px",background:C.bg,borderRadius:10,border:`1px solid ${C.b}`}}>
    <select value={td.status} onChange={e=>onStatusChange(td.id,{status:e.target.value})} style={{background:st?.color+"20",border:`1px solid ${st?.color}40`,borderRadius:6,padding:"3px 6px",color:st?.color,fontSize:10,fontWeight:700,fontFamily:F,cursor:"pointer",outline:"none"}}>{TSTAT.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select>
    <div style={{flex:1,minWidth:0}}>
      <div style={{display:"flex",alignItems:"center",gap:6}}>
        <span style={{fontSize:12,fontWeight:600,color:td.status==="completado"?C.td:C.tx,textDecoration:td.status==="completado"?"line-through":"none"}}>{td.title}</span>
        {td.project_type&&<span style={{fontSize:9,color:C.td,background:C.bg,padding:"1px 5px",borderRadius:4,border:`1px solid ${C.b}`}}>{td.project_type}</span>}
      </div>
      <div style={{fontSize:10,color:C.td,display:"flex",gap:8,marginTop:1,flexWrap:"wrap"}}>
        {showProject&&projName&&<span style={{color:cat.color}}>{cat.icon} {projName}</span>}
        {emp&&<span>👤 {emp.name}</span>}
        {td.start_date&&<span>📅 {td.start_date}</span>}
        {td.end_date&&<span>→ {td.end_date}</span>}
        {td.url&&<a href={td.url} target="_blank" rel="noopener noreferrer" style={{color:C.bl,textDecoration:"none"}}>🔗 Link</a>}
      </div>
    </div>
    <div style={{display:"flex",gap:3,alignItems:"center",flexShrink:0}}>
      <CatBadge cat={td.category||"cliente"}/>
      {pr&&<Badge label={pr.label} color={pr.color}/>}
      {onEdit&&<Btn onClick={()=>onEdit(td)} v="ghost" sz="sm" icon="edit"/>}
      {onDelete&&<button onClick={()=>onDelete(td.id)} style={{background:"none",border:"none",cursor:"pointer",color:C.r,padding:3}}><Ic n="tr" sz={13}/></button>}
    </div>
  </div>;
}

// ─── TIMELINE ───
function Timeline({tasks,employees}){const dated=tasks.filter(t=>t.start_date);if(!dated.length)return<Empty icon="📅" title="Sin fechas" sub="Asigna fechas a las tareas"/>;const sorted=[...dated].sort((a,b)=>a.start_date.localeCompare(b.start_date));const allD=sorted.flatMap(t=>[t.start_date,t.end_date].filter(Boolean));const minD=new Date(Math.min(...allD.map(d=>new Date(d)))),maxD=new Date(Math.max(...allD.map(d=>new Date(d))));const diff=Math.max(Math.ceil((maxD-minD)/864e5),1),dW=Math.max(30,700/diff);const getP=d=>((new Date(d)-minD)/864e5)*dW;const days=[];for(let d=new Date(minD);d<=maxD;d.setDate(d.getDate()+1))days.push(new Date(d));return<div style={{overflowX:"auto",borderRadius:10,border:`1px solid ${C.b}`}}><div style={{minWidth:days.length*dW+200}}><div style={{display:"flex",borderBottom:`1px solid ${C.b}`,position:"sticky",top:0,background:C.s,zIndex:2}}><div style={{width:200,flexShrink:0,padding:"7px 12px",fontSize:10,fontWeight:700,color:C.tm,textTransform:"uppercase",borderRight:`1px solid ${C.b}`}}>Tarea</div><div style={{display:"flex",flex:1}}>{days.map((d,i)=>{const isT=d.toDateString()===new Date().toDateString();return<div key={i} style={{width:dW,flexShrink:0,padding:"5px 2px",textAlign:"center",fontSize:9,fontWeight:isT?700:400,color:isT?C.acc:C.td,borderRight:`1px solid ${C.b}10`,background:isT?C.acc+"08":"transparent"}}><div>{d.toLocaleDateString("es",{weekday:"short"}).slice(0,2)}</div><div style={{fontSize:10,fontWeight:700}}>{d.getDate()}</div></div>})}</div></div>{sorted.map((task,i)=>{const emp=employees.find(e=>e.id===task.assigned_to);const st=TSTAT.find(s=>s.value===task.status);const cat=CATS.find(c=>c.value===(task.category||"cliente"))||CATS[0];const start=getP(task.start_date);const width=task.end_date?Math.max(getP(task.end_date)-start+dW,dW):dW;return<div key={task.id||i} style={{display:"flex",borderBottom:`1px solid ${C.b}10`,minHeight:40,alignItems:"center"}}><div style={{width:200,flexShrink:0,padding:"5px 12px",borderRight:`1px solid ${C.b}`}}><div style={{fontSize:11,fontWeight:600,color:C.tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{task.title}</div><div style={{fontSize:9,color:C.td}}>{emp?.name||"Sin asignar"} · <span style={{color:cat.color}}>{cat.icon}</span></div></div><div style={{flex:1,position:"relative",height:40,display:"flex",alignItems:"center"}}><div style={{position:"absolute",left:start,width,height:20,borderRadius:5,background:`linear-gradient(90deg,${cat.color}50,${cat.color}25)`,border:`1px solid ${cat.color}35`,display:"flex",alignItems:"center",padding:"0 6px"}}><span style={{fontSize:9,fontWeight:600,color:cat.color,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{task.title}</span></div></div></div>})}</div></div>}

// ═══ MAIN APP ═══
export default function App(){
  const[loading,setLoading]=useState(true);const[user,setUser]=useState(null);const[view,setView]=useState("dashboard");
  const[prospects,setProspects]=useState([]);const[clients,setClients]=useState([]);const[employees,setEmployees]=useState([]);
  const[clientUsers,setCU]=useState([]);const[todos,setTodos]=useState([]);const[files,setFiles]=useState([]);
  const[selId,setSelId]=useState(null);const[modal,setModal]=useState(null);const[search,setSearch]=useState("");
  const[loginForm,setLF]=useState({email:"",password:""});const[loginErr,setLE]=useState("");
  const[saving,setSaving]=useState(false);const[syncStatus,setSyncStatus]=useState("");

  const loadAll=useCallback(async()=>{const[p,cl,em,cu,td,fl]=await Promise.all([supabase.from("prospects").select("*").order("created_at",{ascending:false}),supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("employees").select("*").order("created_at",{ascending:false}),supabase.from("client_users").select("*"),supabase.from("todos").select("*").order("created_at",{ascending:false}),supabase.from("files").select("*").order("created_at",{ascending:false})]);if(p.data)setProspects(p.data);if(cl.data)setClients(cl.data);if(em.data)setEmployees(em.data);if(cu.data)setCU(cu.data);if(td.data)setTodos(td.data);if(fl.data)setFiles(fl.data)},[]);
  useEffect(()=>{const sess=localStorage.getItem("wauya_user");if(sess)try{setUser(JSON.parse(sess))}catch{}loadAll().finally(()=>setLoading(false))},[loadAll]);

  const login=async()=>{setLE("");const{data:admin}=await supabase.from("admin_users").select("*").eq("email",loginForm.email).eq("password",loginForm.password).single();if(admin){const u={...admin,role:"master"};delete u.password;setUser(u);localStorage.setItem("wauya_user",JSON.stringify(u));setView("dashboard");return}const{data:cu}=await supabase.from("client_users").select("*").eq("email",loginForm.email).eq("password",loginForm.password).single();if(cu){const u={...cu,role:"client"};setUser(u);localStorage.setItem("wauya_user",JSON.stringify(u));setView("client_portal");return}const{data:emp}=await supabase.from("employees").select("*").eq("email",loginForm.email).eq("password",loginForm.password).single();if(emp){const u={...emp,role:"employee"};setUser(u);localStorage.setItem("wauya_user",JSON.stringify(u));setView("emp_portal");return}setLE("Credenciales incorrectas")};
  const logout=()=>{setUser(null);setView("dashboard");setSelId(null);localStorage.removeItem("wauya_user")};
  const dbAdd=async(table,row)=>{setSaving(true);const{data,error}=await supabase.from(table).insert(row).select().single();setSaving(false);if(error){alert("Error: "+error.message);return null}await loadAll();return data};
  const dbUpd=async(table,id,upd)=>{setSaving(true);await supabase.from(table).update(upd).eq("id",id);setSaving(false);await loadAll()};
  const dbDel=async(table,id)=>{setSaving(true);await supabase.from(table).delete().eq("id",id);setSaving(false);await loadAll()};
  const uploadFile=async(file,ot,oid,ft)=>{setSaving(true);const ext=file.name.split(".").pop();const path=`${ot}/${oid}/${Date.now()}.${ext}`;const{error:e}=await supabase.storage.from("wauya-files").upload(path,file);if(e){setSaving(false);alert(e.message);return}const{data:u}=supabase.storage.from("wauya-files").getPublicUrl(path);await supabase.from("files").insert({owner_type:ot,owner_id:oid,name:file.name,file_type:ft,size:(file.size/1024).toFixed(1)+" KB",storage_path:path,url:u?.publicUrl||""});setSaving(false);await loadAll();setModal(null)};
  const deleteFile=async fid=>{const f=files.find(x=>x.id===fid);if(f?.storage_path)await supabase.storage.from("wauya-files").remove([f.storage_path]);await dbDel("files",fid)};

  const addProspect=async p=>{await dbAdd("prospects",{...p,pipeline_status:"nuevo"});setModal(null)};
  const updProspect=async(id,u)=>dbUpd("prospects",id,u);
  const delProspect=async id=>{if(!confirm("¿Eliminar?"))return;await dbDel("prospects",id);if(selId===id)setSelId(null)};
  const convertProspect=async id=>{const p=prospects.find(x=>x.id===id);if(!p)return;await dbAdd("clients",{name:p.name,company:p.company,email:p.email,phone:p.phone,services:p.services,notes:p.notes,status:"briefing",drive_folder_id:p.drive_folder_id});await dbDel("prospects",id);setSelId(null);setView("clients")};
  const moveProspect=async(id,status)=>dbUpd("prospects",id,{pipeline_status:status});
  const addClient=async cl=>{await dbAdd("clients",cl);setModal(null)};
  const updClient=async(id,u)=>dbUpd("clients",id,u);
  const delClient=async id=>{if(!confirm("¿Eliminar?"))return;await dbDel("clients",id);if(selId===id)setSelId(null)};
  const addCU=async(cid,u)=>{await dbAdd("client_users",{client_id:cid,...u});setModal(null)};
  const delCU=async uid=>{if(!confirm("¿Eliminar?"))return;await dbDel("client_users",uid)};
  const addEmp=async e=>{await dbAdd("employees",e);setModal(null)};
  const delEmp=async id=>{if(!confirm("¿Eliminar?"))return;await dbDel("employees",id)};
  const addTodo=async td=>{await dbAdd("todos",td);setModal(null)};
  const updTodo=async(id,u)=>dbUpd("todos",id,u);
  const delTodo=async id=>{if(!confirm("¿Eliminar?"))return;await dbDel("todos",id)};

  const syncFromDrive=async folderUrl=>{const fid=extractFolderId(folderUrl);if(!fid){alert("URL no válida");return}setSaving(true);setSyncStatus("Escaneando...");try{const res=await fetch(`/api/drive?action=list&folderId=${fid}`);const items=await res.json();if(items.error){alert(items.error);setSaving(false);setSyncStatus("");return}const folders=items.filter(f=>f.mimeType==="application/vnd.google-apps.folder");let cr=0,sk=0;for(const fo of folders){if(prospects.find(p=>(p.company||"").toLowerCase()===fo.name.toLowerCase())||clients.find(c=>(c.company||"").toLowerCase()===fo.name.toLowerCase())){sk++;continue}await supabase.from("prospects").insert({name:fo.name,company:fo.name,drive_folder_id:fo.id,pipeline_status:"nuevo"});cr++}await loadAll();setSyncStatus("");setSaving(false);setModal(null);localStorage.setItem("wauya_leads_folder",folderUrl);alert(`✅ ${cr} creados · ⏭ ${sk} existían`)}catch(e){alert(e.message);setSaving(false);setSyncStatus("")}};

  const handleQBR=async client=>{if(!client.sheet_id){generateQBR(client,null);return}try{const r=await fetch(`/api/sheets?sheetId=${client.sheet_id}&range=KPIs!A1:Z50`);const d=await r.json();generateQBR(client,Array.isArray(d)?d:null)}catch{generateQBR(client,null)}};

  const prospFiles=pid=>files.filter(f=>f.owner_type==="prospect"&&f.owner_id===pid);
  const clientFiles=cid=>files.filter(f=>f.owner_type==="client"&&f.owner_id===cid);
  const stats=useMemo(()=>{const tt=todos.length,ct=todos.filter(x=>x.status==="completado").length,pt=todos.filter(x=>x.status==="pendiente").length,ip=todos.filter(x=>x.status==="en_progreso").length;const sc=STATUS_OPTS.map(s=>({...s,count:clients.filter(x=>x.status===s.value).length}));const el=employees.map(e=>({...e,tc:todos.filter(td=>td.assigned_to===e.id&&td.status!=="completado").length}));return{tt,ct,pt,ip,sc,el}},[todos,clients,employees]);

  // LOGIN
  if(!user&&!loading)return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"}}><style>{CSS}</style><div style={{animation:"fadeUp .5s ease",textAlign:"center",width:"90%",maxWidth:380}}><div style={{marginBottom:36}}><div style={{fontFamily:D,fontSize:44,fontWeight:800,color:C.tx}}>W<span style={{color:C.acc}}>.</span></div><div style={{fontFamily:D,fontSize:12,fontWeight:500,color:C.tm,letterSpacing:".15em",textTransform:"uppercase"}}>Wauya Platform</div></div><div style={{background:C.s,borderRadius:18,border:`1px solid ${C.b}`,padding:28,textAlign:"left"}}><h2 style={{fontFamily:D,fontSize:18,fontWeight:700,color:C.tx,marginBottom:22}}>Iniciar Sesión</h2><div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Email" type="email" value={loginForm.email} onChange={e=>setLF({...loginForm,email:e.target.value})} placeholder="tu@email.com" onKeyDown={e=>e.key==="Enter"&&login()}/><Inp label="Contraseña" type="password" value={loginForm.password} onChange={e=>setLF({...loginForm,password:e.target.value})} placeholder="••••••••" onKeyDown={e=>e.key==="Enter"&&login()}/>{loginErr&&<div style={{color:C.r,fontSize:12}}>{loginErr}</div>}<Btn onClick={login} sz="lg" style={{width:"100%",justifyContent:"center",marginTop:6}}>Ingresar</Btn></div></div></div></div>;
  if(loading)return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"}}><style>{CSS}</style><div style={{fontFamily:D,fontSize:28,color:C.acc,animation:"pulse 1.2s infinite"}}>W.</div></div>;

  // EMPLOYEE PORTAL — shows ALL tasks (clients + proposals + internal)
  if(user?.role==="employee"){
    const myTodos=todos.filter(td=>td.assigned_to===user.id);
    const byCategory={cliente:[],propuesta:[],interno:[]};
    myTodos.forEach(td=>{const cat=td.category||"cliente";if(!byCategory[cat])byCategory[cat]=[];byCategory[cat].push(td)});
    const pending=myTodos.filter(td=>td.status!=="completado").length;
    return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh"}}><style>{CSS}</style>
      <div style={{borderBottom:`1px solid ${C.b}`,padding:"14px 28px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{fontFamily:D,fontSize:22,fontWeight:800,color:C.tx}}>W<span style={{color:C.acc}}>.</span></span><span style={{color:C.td}}>|</span><span style={{fontSize:13,color:C.tm}}>Portal Empleado</span></div><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{fontSize:12,color:C.tm}}>{user.name}</span><Btn onClick={logout} v="ghost" icon="out" sz="sm">Salir</Btn></div></div>
      <div style={{maxWidth:900,margin:"0 auto",padding:"32px 20px",animation:"fadeUp .4s ease"}}>
        <h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx,marginBottom:6}}>Hola, {user.name} 👋</h1>
        <p style={{fontSize:13,color:C.tm,marginBottom:28}}>{pending} tareas pendientes</p>
        {myTodos.length===0?<Empty icon="✅" title="Sin tareas" sub="No tienes tareas asignadas"/>:
          CATS.map(cat=>{const catTodos=byCategory[cat.value]||[];if(!catTodos.length)return null;
            return<Card key={cat.value} style={{marginBottom:16}}>
              <h3 style={{fontFamily:D,fontSize:14,fontWeight:700,color:cat.color,marginBottom:14}}>{cat.icon} {cat.label}s ({catTodos.length})</h3>
              <div style={{display:"flex",flexDirection:"column",gap:6}}>
                {catTodos.map(td=>{const pr=PRIOS.find(p=>p.value===td.priority);const st=TSTAT.find(s=>s.value===td.status);
                  const projName=td.client_id?clients.find(x=>x.id===td.client_id)?.company:td.prospect_id?prospects.find(x=>x.id===td.prospect_id)?.company:"";
                  return<div key={td.id} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",background:C.bg,borderRadius:10,border:`1px solid ${C.b}`}}>
                    <button onClick={async()=>{const nx=td.status==="pendiente"?"en_progreso":td.status==="en_progreso"?"completado":"pendiente";await updTodo(td.id,{status:nx})}} style={{width:22,height:22,borderRadius:6,border:`2px solid ${st?.color}`,background:td.status==="completado"?C.g:"transparent",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,color:"#fff"}}>{td.status==="completado"&&<Ic n="check" sz={12}/>}</button>
                    <div style={{flex:1}}>
                      <div style={{fontSize:13,fontWeight:500,color:td.status==="completado"?C.td:C.tx,textDecoration:td.status==="completado"?"line-through":"none"}}>{td.title}</div>
                      <div style={{fontSize:10,color:C.td,display:"flex",gap:8,marginTop:2,flexWrap:"wrap"}}>
                        {projName&&<span style={{color:cat.color}}>{projName}</span>}
                        {td.project_type&&<span>📋 {td.project_type}</span>}
                        {td.end_date&&<span>📅 {td.end_date}</span>}
                        {td.url&&<a href={td.url} target="_blank" rel="noopener noreferrer" style={{color:C.bl,textDecoration:"none"}}>🔗 Link</a>}
                      </div>
                    </div>
                    <div style={{display:"flex",gap:6,alignItems:"center",flexShrink:0}}>{pr&&<Badge label={pr.label} color={pr.color}/>}</div>
                  </div>})}
              </div>
            </Card>})}
      </div></div>;
  }

  // CLIENT PORTAL
  if(user?.role==="client"){const cl=clients.find(x=>x.id===user.client_id);if(!cl)return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"}}><style>{CSS}</style><div style={{textAlign:"center"}}><div style={{fontSize:48,marginBottom:16}}>🔒</div><h2 style={{fontFamily:D,color:C.tx}}>Sin acceso</h2><Btn onClick={logout} style={{marginTop:16}}>Salir</Btn></div></div>;
    return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh"}}><style>{CSS}</style>
      <div style={{borderBottom:`1px solid ${C.b}`,padding:"14px 28px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{fontFamily:D,fontSize:22,fontWeight:800,color:C.tx}}>W<span style={{color:C.acc}}>.</span></span><span style={{color:C.td}}>|</span><span style={{fontSize:13,color:C.tm}}>Portal Cliente</span></div><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{fontSize:12,color:C.tm}}>{user.name}</span><Btn onClick={logout} v="ghost" icon="out" sz="sm">Salir</Btn></div></div>
      <div style={{maxWidth:900,margin:"0 auto",padding:"36px 20px",animation:"fadeUp .4s ease"}}>
        <h1 style={{fontFamily:D,fontSize:26,fontWeight:700,color:C.tx,marginBottom:6}}>Hola, {user.name} 👋</h1><p style={{fontSize:13,color:C.tm,marginBottom:28}}>Portal de {cl.company||cl.name}</p>
        <Card style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h3 style={{fontFamily:D,fontSize:15,fontWeight:600,color:C.tx}}>Estado</h3><SBadge status={cl.status}/></div><div style={{display:"flex",gap:3,borderRadius:6,overflow:"hidden"}}>{STATUS_OPTS.map((s,i)=><div key={s.value} style={{flex:1,height:5,background:i<=STATUS_OPTS.findIndex(x=>x.value===cl.status)?s.color:C.b}}/>)}</div></Card>
        <Card style={{marginBottom:20}}><Approvals clientId={cl.id} readOnly/></Card>
        {cl.sheet_id&&<Card style={{marginBottom:20}}><KPIDashboard sheetId={cl.sheet_id} readOnly/></Card>}
        {cl.calendar_sheet_id&&<Card style={{marginBottom:20}}><h3 style={{fontFamily:D,fontSize:15,fontWeight:600,color:C.tx,marginBottom:14}}>📅 Calendario</h3><ContentCalendar sheetId={cl.calendar_sheet_id} readOnly/></Card>}
        <Card style={{marginBottom:20}}><h3 style={{fontFamily:D,fontSize:15,fontWeight:600,color:C.tx,marginBottom:16}}>Entregables ({clientFiles(cl.id).length})</h3>{clientFiles(cl.id).length===0?<Empty icon="📦" title="Sin entregables"/>:<div style={{display:"flex",flexDirection:"column",gap:8}}>{clientFiles(cl.id).map(fl=><FileCard key={fl.id} file={fl} showDel={false}/>)}</div>}</Card>
        {cl.drive_folder_id&&<Card><h3 style={{fontFamily:D,fontSize:15,fontWeight:600,color:C.tx,marginBottom:14}}>📂 Archivos</h3><DriveFiles ownerType="client" ownerId={cl.id} currentFolderId={cl.drive_folder_id} readOnly/></Card>}
      </div></div>;
  }

  // ═══ ADMIN ═══
  const nav=[{key:"dashboard",label:"Dashboard",icon:"dash"},{key:"pipeline",label:"Pipeline",icon:"pipe",cnt:prospects.length},{key:"prospects",label:"Prospectos",icon:"prosp"},{key:"clients",label:"Clientes",icon:"cli",cnt:clients.length},{key:"employees",label:"Empleados",icon:"emp",cnt:employees.length},{key:"timeline",label:"Cronograma",icon:"cal",cnt:todos.filter(t=>t.status!=="completado").length},{key:"users",label:"Usuarios",icon:"usr"},{key:"settings",label:"Configuración",icon:"lock"}];
  const sp=prospects.find(p=>p.id===selId);const sc=clients.find(x=>x.id===selId);
  const filt=l=>l.filter(x=>(x.name+(x.company||"")+(x.email||"")).toLowerCase().includes(search.toLowerCase()));

  return<div style={{fontFamily:F,background:C.bg,minHeight:"100vh",display:"flex"}}><style>{CSS}</style>
    {saving&&<div style={{position:"fixed",top:12,right:12,background:C.acc,color:"#000",padding:"6px 14px",borderRadius:8,fontSize:11,fontWeight:700,zIndex:2000,animation:"fadeIn .2s"}}>{syncStatus||"Guardando..."}</div>}
    <div style={{width:220,borderRight:`1px solid ${C.b}`,display:"flex",flexDirection:"column",flexShrink:0,background:C.s,position:"sticky",top:0,height:"100vh"}}><div style={{padding:"20px 18px 28px",borderBottom:`1px solid ${C.b}`}}><div style={{fontFamily:D,fontSize:26,fontWeight:800,color:C.tx}}>W<span style={{color:C.acc}}>.</span></div><div style={{fontSize:10,color:C.td,marginTop:1,letterSpacing:".1em",textTransform:"uppercase"}}>Project Manager</div></div><nav style={{flex:1,padding:"12px 8px",display:"flex",flexDirection:"column",gap:1,overflow:"auto"}}>{nav.map(i=><button key={i.key} onClick={()=>{setView(i.key);setSelId(null);setSearch("")}} style={{display:"flex",alignItems:"center",gap:9,padding:"9px 10px",border:"none",borderRadius:8,background:view===i.key?C.acc+"12":"transparent",color:view===i.key?C.acc:C.tm,fontFamily:F,fontSize:12,fontWeight:500,cursor:"pointer",textAlign:"left",width:"100%"}}><Ic n={i.icon} sz={17}/>{i.label}{i.cnt>0&&<span style={{marginLeft:"auto",fontSize:10,background:C.bg,padding:"1px 6px",borderRadius:8,color:C.td}}>{i.cnt}</span>}</button>)}</nav><div style={{padding:"14px 10px",borderTop:`1px solid ${C.b}`}}><div style={{display:"flex",alignItems:"center",gap:9,marginBottom:10,padding:"0 4px"}}><div style={{width:28,height:28,borderRadius:7,background:`linear-gradient(135deg,${C.acc},${C.accD})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,color:C.bg}}>A</div><div><div style={{fontSize:11,fontWeight:600,color:C.tx}}>Admin</div><div style={{fontSize:9,color:C.td}}>Master</div></div></div><Btn onClick={logout} v="ghost" icon="out" sz="sm" style={{width:"100%",justifyContent:"center"}}>Cerrar Sesión</Btn></div></div>

    <div style={{flex:1,overflow:"auto"}}><div style={{padding:"24px 32px",animation:"fadeIn .25s ease"}}>

      {/* DASHBOARD */}
      {view==="dashboard"&&<div><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx,marginBottom:4}}>Dashboard</h1><p style={{fontSize:13,color:C.tm,marginBottom:24}}>Vista general</p><div style={{display:"flex",flexWrap:"wrap",gap:12,marginBottom:24}}><Stat label="Prospectos" value={prospects.length} icon="🎯" color={C.w}/><Stat label="Clientes" value={clients.length} icon="💼" color={C.acc}/><Stat label="Empleados" value={employees.length} icon="👤" color={C.p}/><Stat label="Tareas" value={todos.length} icon="📋" color={C.bl}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:700,color:C.tx,marginBottom:16}}>Proyectos</h3><div style={{display:"flex",alignItems:"center",gap:20}}><Donut data={stats.sc.map(s=>({value:s.count,color:s.color}))}/><div style={{display:"flex",flexDirection:"column",gap:5}}>{stats.sc.map(s=><div key={s.value} style={{display:"flex",alignItems:"center",gap:7,fontSize:11}}><div style={{width:8,height:8,borderRadius:2,background:s.color}}/><span style={{color:C.tm}}>{s.label}</span><span style={{color:C.tx,fontWeight:700,marginLeft:"auto"}}>{s.count}</span></div>)}</div></div></Card><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:700,color:C.tx,marginBottom:16}}>Tareas por categoría</h3><MiniBar data={CATS.map(c=>({label:c.label,value:todos.filter(t=>(t.category||"cliente")===c.value&&t.status!=="completado").length,color:c.color}))} height={120}/></Card></div></div>}

      {/* PIPELINE */}
      {view==="pipeline"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>Pipeline</h1><div style={{display:"flex",gap:8}}><Btn onClick={()=>setModal("sync_drive")} v="secondary" icon="sync">Sync Drive</Btn><Btn onClick={()=>setModal("add_prospect")} icon="plus">Nuevo</Btn></div></div><Pipeline prospects={prospects} onMove={moveProspect} onSelect={id=>{setSelId(id);setView("prospects")}}/></div>}

      {/* PROSPECTS */}
      {view==="prospects"&&!selId&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>Prospectos</h1><div style={{display:"flex",gap:8}}><Btn onClick={()=>setModal("sync_drive")} v="secondary" icon="sync">Sync</Btn><Btn onClick={()=>setModal("add_prospect")} icon="plus">Nuevo</Btn></div></div><div style={{position:"relative",marginBottom:18}}><div style={{position:"absolute",left:11,top:"50%",transform:"translateY(-50%)",color:C.td}}><Ic n="srch" sz={15}/></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..." style={{width:"100%",background:C.bg,border:`1px solid ${C.b}`,borderRadius:10,padding:"9px 12px 9px 34px",color:C.tx,fontSize:12,fontFamily:F,outline:"none"}}/></div>{filt(prospects).length===0?<Empty icon="🎯" title="Sin prospectos"/>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:12}}>{filt(prospects).map(p=><Card key={p.id} hover onClick={()=>setSelId(p.id)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><div><div style={{fontFamily:D,fontSize:14,fontWeight:600,color:C.tx}}>{p.company||p.name}</div><div style={{fontSize:11,color:C.tm,marginTop:1}}>{p.name}</div></div>{p.drive_folder_id&&<span style={{fontSize:10,color:C.g}}>📁</span>}</div>{p.email&&<div style={{fontSize:11,color:C.td}}>✉ {p.email}</div>}<div style={{display:"flex",gap:8,marginTop:8,fontSize:10,color:C.td}}><span>📋 {todos.filter(t=>t.prospect_id===p.id).length} tareas</span></div></Card>)}</div>}</div>}

      {/* PROSPECT DETAIL — now with tasks */}
      {view==="prospects"&&selId&&sp&&<div><button onClick={()=>setSelId(null)} style={{display:"flex",alignItems:"center",gap:5,background:"none",border:"none",color:C.tm,cursor:"pointer",fontSize:12,marginBottom:18,padding:0,fontFamily:F}}><Ic n="back" sz={15}/>Volver</button><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}><div><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>{sp.company||sp.name}</h1><p style={{fontSize:12,color:C.tm,marginTop:2}}>{sp.name} · {sp.email}</p></div><div style={{display:"flex",gap:8}}><Btn onClick={()=>convertProspect(sp.id)} sz="sm">Convertir a Cliente</Btn><Btn onClick={()=>delProspect(sp.id)} v="danger" sz="sm" icon="tr"/></div></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:20}}><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:10}}>Info</h3>{sp.phone&&<div style={{fontSize:12,color:C.tm,marginBottom:4}}>📱 {sp.phone}</div>}{sp.services&&<div style={{fontSize:12,color:C.tm}}>🎯 {sp.services}</div>}</Card><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:10}}>Notas</h3><textarea value={sp.notes||""} onBlur={e=>updProspect(sp.id,{notes:e.target.value})} onChange={e=>{const v=e.target.value;setProspects(pr=>pr.map(x=>x.id===sp.id?{...x,notes:v}:x))}} placeholder="Notas..." style={{width:"100%",background:C.bg,border:`1px solid ${C.b}`,borderRadius:8,padding:8,color:C.tx,fontSize:12,fontFamily:F,outline:"none",resize:"vertical",minHeight:70}}/></Card></div>
        {/* TASKS FOR PROSPECT */}
        <Card style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx}}>Tareas ({todos.filter(t=>t.prospect_id===sp.id).length})</h3><Btn onClick={()=>setModal({type:"add_todo_global",defaults:{category:"propuesta",prospect_id:sp.id}})} v="secondary" sz="sm" icon="plus">Nueva</Btn></div>{todos.filter(t=>t.prospect_id===sp.id).length===0?<p style={{fontSize:11,color:C.td}}>Sin tareas</p>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{todos.filter(t=>t.prospect_id===sp.id).map(td=><TaskRow key={td.id} td={td} employees={employees} clients={clients} prospects={prospects} onStatusChange={(id,u)=>updTodo(id,u)} onEdit={t=>setModal({type:"edit_todo",todo:t})} onDelete={delTodo}/>)}</div>}</Card>
        <Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx}}>Archivos ({prospFiles(sp.id).length})</h3><Btn onClick={()=>setModal("upload_pf")} v="secondary" sz="sm" icon="plus">Subir</Btn></div>{prospFiles(sp.id).length===0?<Empty icon="📁" title="Sin archivos"/>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{prospFiles(sp.id).map(fl=><FileCard key={fl.id} file={fl} onDelete={deleteFile}/>)}</div>}</Card>
        <Card style={{marginTop:20}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:14}}>📂 Google Drive</h3><DriveFiles ownerType="prospect" ownerId={sp.id} currentFolderId={sp.drive_folder_id} onUpdate={loadAll}/></Card>
      </div>}

      {/* CLIENTS LIST */}
      {view==="clients"&&!selId&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>Clientes</h1><Btn onClick={()=>setModal("add_client")} icon="plus">Nuevo</Btn></div><div style={{position:"relative",marginBottom:18}}><div style={{position:"absolute",left:11,top:"50%",transform:"translateY(-50%)",color:C.td}}><Ic n="srch" sz={15}/></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..." style={{width:"100%",background:C.bg,border:`1px solid ${C.b}`,borderRadius:10,padding:"9px 12px 9px 34px",color:C.tx,fontSize:12,fontFamily:F,outline:"none"}}/></div>{filt(clients).length===0?<Empty icon="💼" title="Sin clientes"/>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{filt(clients).map(cl=><Card key={cl.id} hover onClick={()=>setSelId(cl.id)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><div><div style={{fontFamily:D,fontSize:14,fontWeight:600,color:C.tx}}>{cl.company||cl.name}</div><div style={{fontSize:11,color:C.tm,marginTop:1}}>{cl.name}</div></div><SBadge status={cl.status}/></div>{cl.services&&<div style={{fontSize:11,color:C.td,marginBottom:6}}>🎯 {cl.services}</div>}<div style={{display:"flex",gap:10,fontSize:10,color:C.td}}><span><Ic n="todo" sz={11}/>{todos.filter(td=>td.client_id===cl.id).length}</span><span><Ic n="usr" sz={11}/>{clientUsers.filter(u=>u.client_id===cl.id).length}</span></div></Card>)}</div>}</div>}

      {/* CLIENT DETAIL */}
      {view==="clients"&&selId&&sc&&<div>
        <button onClick={()=>setSelId(null)} style={{display:"flex",alignItems:"center",gap:5,background:"none",border:"none",color:C.tm,cursor:"pointer",fontSize:12,marginBottom:18,padding:0,fontFamily:F}}><Ic n="back" sz={15}/>Volver</button>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}><div><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>{sc.company||sc.name}</h1><p style={{fontSize:12,color:C.tm,marginTop:2}}>{sc.name} · {sc.email}</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Btn onClick={()=>handleQBR(sc)} v="secondary" sz="sm">📊 QBR</Btn><Sel value={sc.status} onChange={e=>updClient(sc.id,{status:e.target.value})} options={STATUS_OPTS} style={{fontSize:11,padding:"6px 10px"}}/><Btn onClick={()=>delClient(sc.id)} v="danger" sz="sm" icon="tr"/></div></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:20}}><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:10}}>Info</h3>{sc.phone&&<div style={{fontSize:12,color:C.tm,marginBottom:4}}>📱 {sc.phone}</div>}{sc.services&&<div style={{fontSize:12,color:C.tm}}>🎯 {sc.services}</div>}</Card><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:10}}>Notas</h3><textarea value={sc.notes||""} onBlur={e=>updClient(sc.id,{notes:e.target.value})} onChange={e=>{const v=e.target.value;setClients(cl=>cl.map(x=>x.id===sc.id?{...x,notes:v}:x))}} placeholder="Notas..." style={{width:"100%",background:C.bg,border:`1px solid ${C.b}`,borderRadius:8,padding:8,color:C.tx,fontSize:12,fontFamily:F,outline:"none",resize:"vertical",minHeight:70}}/></Card></div>
        <Card style={{marginBottom:20}}><Approvals clientId={sc.id}/></Card>
        <Card style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx}}>Usuarios ({clientUsers.filter(u=>u.client_id===sc.id).length})</h3><Btn onClick={()=>setModal("add_cu")} v="secondary" sz="sm" icon="plus">Crear</Btn></div>{clientUsers.filter(u=>u.client_id===sc.id).length===0?<p style={{fontSize:11,color:C.td}}>Sin usuarios</p>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{clientUsers.filter(u=>u.client_id===sc.id).map(u=><div key={u.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 12px",background:C.bg,borderRadius:8,border:`1px solid ${C.b}`}}><div><div style={{fontSize:12,fontWeight:500,color:C.tx}}>{u.name}</div><div style={{fontSize:10,color:C.td}}>{u.email} · 🔑 {u.password}</div></div><button onClick={()=>delCU(u.id)} style={{background:"none",border:"none",cursor:"pointer",color:C.r,padding:4}}><Ic n="tr" sz={13}/></button></div>)}</div>}</Card>
        <Card style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx}}>Tareas ({todos.filter(td=>td.client_id===sc.id).length})</h3><Btn onClick={()=>setModal({type:"add_todo_global",defaults:{category:"cliente",client_id:sc.id}})} v="secondary" sz="sm" icon="plus">Nueva</Btn></div>{todos.filter(td=>td.client_id===sc.id).length===0?<p style={{fontSize:11,color:C.td}}>Sin tareas</p>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{todos.filter(td=>td.client_id===sc.id).map(td=><TaskRow key={td.id} td={td} employees={employees} clients={clients} prospects={prospects} onStatusChange={(id,u)=>updTodo(id,u)} onEdit={t=>setModal({type:"edit_todo",todo:t})} onDelete={delTodo}/>)}</div>}</Card>
        <Card style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx}}>Entregables ({clientFiles(sc.id).length})</h3><Btn onClick={()=>setModal("upload_del")} v="secondary" sz="sm" icon="plus">Subir</Btn></div>{clientFiles(sc.id).length===0?<Empty icon="📦" title="Sin entregables"/>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{clientFiles(sc.id).map(fl=><FileCard key={fl.id} file={fl} onDelete={deleteFile}/>)}</div>}</Card>
        <Card style={{marginBottom:20}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:14}}>📅 Calendario</h3><ContentCalendar sheetId={sc.calendar_sheet_id} onLink={async sid=>{await dbUpd("clients",sc.id,{calendar_sheet_id:sid})}} onUnlink={async()=>{await dbUpd("clients",sc.id,{calendar_sheet_id:null})}}/></Card>
        <Card style={{marginBottom:20}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:14}}>📂 Google Drive</h3><DriveFiles ownerType="client" ownerId={sc.id} currentFolderId={sc.drive_folder_id} onUpdate={loadAll}/></Card>
        <Card><KPIDashboard sheetId={sc.sheet_id} onLink={async sid=>{await dbUpd("clients",sc.id,{sheet_id:sid})}} onUnlink={async()=>{await dbUpd("clients",sc.id,{sheet_id:null})}}/></Card>
      </div>}

      {/* EMPLOYEES */}
      {view==="employees"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>Empleados</h1><Btn onClick={()=>setModal("add_emp")} icon="plus">Nuevo</Btn></div>{employees.length===0?<Empty icon="👤" title="Sin empleados"/>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{employees.map(e=>{const tasks=todos.filter(td=>td.assigned_to===e.id);const done=tasks.filter(td=>td.status==="completado").length;const byC={};tasks.forEach(t=>{const c=t.category||"cliente";byC[c]=(byC[c]||0)+1});return<Card key={e.id}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{width:36,height:36,borderRadius:10,background:`linear-gradient(135deg,${C.p},${C.bl})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:"#fff"}}>{e.name?.charAt(0)?.toUpperCase()}</div><div><div style={{fontFamily:D,fontSize:14,fontWeight:600,color:C.tx}}>{e.name}</div><div style={{fontSize:10,color:C.td}}>{e.role||"Empleado"}</div></div></div><button onClick={()=>delEmp(e.id)} style={{background:"none",border:"none",cursor:"pointer",color:C.r,padding:3}}><Ic n="tr" sz={14}/></button></div><div style={{fontSize:11,color:C.tm,marginBottom:8}}>✉ {e.email} · 🔑 {e.password}</div><div style={{display:"flex",gap:8,fontSize:10,color:C.td,flexWrap:"wrap"}}><span>{tasks.length} tareas</span><span style={{color:C.g}}>· {done} completadas</span>{Object.entries(byC).map(([k,v])=>{const ct=CATS.find(c=>c.value===k);return<span key={k} style={{color:ct?.color}}>{ct?.icon} {v}</span>})}</div>{tasks.length>0&&<div style={{marginTop:6,background:C.bg,borderRadius:6,overflow:"hidden",height:4,display:"flex"}}><div style={{width:`${(done/tasks.length)*100}%`,background:C.g,transition:"width .3s"}}/></div>}</Card>})}</div>}</div>}

      {/* CRONOGRAMA — ALL tasks, grouped by category */}
      {view==="timeline"&&<div>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}>
          <h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx}}>Cronograma</h1>
          <Btn onClick={()=>setModal({type:"add_todo_global",defaults:{}})} icon="plus">Nueva tarea</Btn>
        </div>
        <p style={{fontSize:12,color:C.tm,marginBottom:20}}>Todas las tareas: clientes, propuestas e internas</p>
        {/* Stats */}
        <div style={{display:"flex",gap:12,marginBottom:20,flexWrap:"wrap"}}>{CATS.map(cat=>{const catTodos=todos.filter(t=>(t.category||"cliente")===cat.value);const pending=catTodos.filter(t=>t.status!=="completado").length;return<div key={cat.value} style={{background:C.s,borderRadius:10,border:`1px solid ${C.b}`,padding:"10px 16px",display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:16}}>{cat.icon}</span><div><div style={{fontSize:10,color:C.tm,fontFamily:F}}>{cat.label}s</div><div style={{fontSize:18,fontWeight:800,color:cat.color,fontFamily:D}}>{pending}</div></div></div>})}</div>
        {/* Timeline view per category */}
        {CATS.map(cat=>{const catTodos=todos.filter(t=>(t.category||"cliente")===cat.value);if(!catTodos.length)return null;
          // Group by project
          const groups={};catTodos.forEach(td=>{
            let key,name;
            if(td.client_id){const cl=clients.find(x=>x.id===td.client_id);key=td.client_id;name=cl?.company||cl?.name||"Cliente"}
            else if(td.prospect_id){const pr=prospects.find(x=>x.id===td.prospect_id);key=td.prospect_id;name=pr?.company||pr?.name||"Prospecto"}
            else{key="interno";name="Interno"}
            if(!groups[key])groups[key]={name,todos:[]};groups[key].todos.push(td)
          });
          return<div key={cat.value} style={{marginBottom:24}}>
            <h3 style={{fontFamily:D,fontSize:16,fontWeight:700,color:cat.color,marginBottom:12}}>{cat.icon} {cat.label}s ({catTodos.filter(t=>t.status!=="completado").length} pendientes)</h3>
            {Object.entries(groups).map(([k,{name,todos:tds}])=><div key={k} style={{marginBottom:16}}>
              <div style={{fontSize:13,fontWeight:600,color:C.tx,marginBottom:8,paddingLeft:4}}>{name}</div>
              <Timeline tasks={tds} employees={employees}/>
            </div>)}
          </div>})}
        {todos.length===0&&<Empty icon="📅" title="Sin tareas" sub="Crea tareas para verlas aquí"/>}
      </div>}

      {/* USERS */}
      {view==="users"&&<div><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx,marginBottom:20}}>Usuarios</h1><Card style={{marginBottom:16}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:700,color:C.acc,marginBottom:12}}>Master</h3><div style={{display:"flex",alignItems:"center",gap:12,padding:"8px 12px",background:C.bg,borderRadius:8,border:`1px solid ${C.b}`}}><div style={{width:30,height:30,borderRadius:8,background:`linear-gradient(135deg,${C.acc},${C.accD})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:C.bg}}>A</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:500,color:C.tx}}>{user?.name||"Admin"}</div><div style={{fontSize:10,color:C.td}}>{user?.email}</div></div><Badge label="MASTER" color={C.acc}/><Btn onClick={()=>setView("settings")} v="ghost" sz="sm" icon="edit">Editar</Btn></div></Card><Card style={{marginBottom:16}}><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:12}}>Empleados ({employees.length})</h3>{employees.length===0?<p style={{fontSize:11,color:C.td}}>Sin empleados</p>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{employees.map(e=><div key={e.id} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",background:C.bg,borderRadius:8,border:`1px solid ${C.b}`}}><div style={{width:26,height:26,borderRadius:6,background:C.pBg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:600,color:C.p}}>{e.name?.charAt(0)?.toUpperCase()}</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:500,color:C.tx}}>{e.name}</div><div style={{fontSize:10,color:C.td}}>{e.email} · 🔑 {e.password}</div></div><Badge label="EMPLEADO" color={C.p}/><Btn onClick={()=>setModal({type:"edit_user",table:"employees",user:e})} v="ghost" sz="sm" icon="edit"/></div>)}</div>}</Card><Card><h3 style={{fontFamily:D,fontSize:13,fontWeight:600,color:C.tx,marginBottom:12}}>Clientes ({clientUsers.length})</h3>{clientUsers.length===0?<p style={{fontSize:11,color:C.td}}>Sin usuarios</p>:<div style={{display:"flex",flexDirection:"column",gap:6}}>{clientUsers.map(u=>{const cl=clients.find(x=>x.id===u.client_id);return<div key={u.id} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",background:C.bg,borderRadius:8,border:`1px solid ${C.b}`}}><div style={{width:26,height:26,borderRadius:6,background:C.blBg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:600,color:C.bl}}>{u.name?.charAt(0)?.toUpperCase()}</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:500,color:C.tx}}>{u.name}</div><div style={{fontSize:10,color:C.td}}>{u.email} · {cl?.company||"—"} · 🔑 {u.password}</div></div><Badge label="CLIENTE" color={C.bl}/><Btn onClick={()=>setModal({type:"edit_user",table:"client_users",user:u})} v="ghost" sz="sm" icon="edit"/></div>})}</div>}</Card></div>}

      {/* SETTINGS */}
      {view==="settings"&&<SettingsView user={user} onSave={async upd=>{setSaving(true);await supabase.from("admin_users").update(upd).eq("id",user.id);const nu={...user,...upd};delete nu.password;setUser(nu);localStorage.setItem("wauya_user",JSON.stringify(nu));setSaving(false);alert("Actualizado")}} onBack={()=>setView("users")}/>}

    </div></div>

    {/* MODALS */}
    {modal==="sync_drive"&&<Mod title="Sincronizar desde Drive" onClose={()=>setModal(null)}><SyncForm onSync={syncFromDrive} onCancel={()=>setModal(null)} saving={saving} syncStatus={syncStatus}/></Mod>}
    {modal==="add_prospect"&&<Mod title="Nuevo Prospecto" onClose={()=>setModal(null)}><FP onDone={addProspect} onX={()=>setModal(null)}/></Mod>}
    {modal==="add_client"&&<Mod title="Nuevo Cliente" onClose={()=>setModal(null)}><FC onDone={addClient} onX={()=>setModal(null)}/></Mod>}
    {modal==="add_cu"&&sc&&<Mod title={`Usuario - ${sc.company||sc.name}`} onClose={()=>setModal(null)}><FCU onDone={u=>addCU(sc.id,u)} onX={()=>setModal(null)}/></Mod>}
    {modal==="add_emp"&&<Mod title="Nuevo Empleado" onClose={()=>setModal(null)}><FE onDone={addEmp} onX={()=>setModal(null)}/></Mod>}
    {modal?.type==="add_todo_global"&&<Mod title="Nueva Tarea" onClose={()=>setModal(null)} w={600}><FTGlobal clients={clients} prospects={prospects} emps={employees} defaults={modal.defaults} onDone={addTodo} onX={()=>setModal(null)}/></Mod>}
    {modal?.type==="edit_todo"&&<Mod title="Editar Tarea" onClose={()=>setModal(null)} w={600}><FTGlobal clients={clients} prospects={prospects} emps={employees} init={modal.todo} onDone={async u=>{await updTodo(modal.todo.id,u);setModal(null)}} onX={()=>setModal(null)} isEdit/></Mod>}
    {modal==="upload_pf"&&sp&&<Mod title="Subir Archivo" onClose={()=>setModal(null)}><FU types={PROSP_TYPES} onDone={(f,t)=>uploadFile(f,"prospect",sp.id,t)} onX={()=>setModal(null)}/></Mod>}
    {modal==="upload_del"&&sc&&<Mod title="Subir Entregable" onClose={()=>setModal(null)}><FU types={DEL_TYPES} onDone={(f,t)=>uploadFile(f,"client",sc.id,t)} onX={()=>setModal(null)}/></Mod>}
    {modal?.type==="edit_user"&&<Mod title="Editar Usuario" onClose={()=>setModal(null)}><FEditUser user={modal.user} table={modal.table} onDone={async upd=>{await dbUpd(modal.table,modal.user.id,upd);setModal(null)}} onX={()=>setModal(null)}/></Mod>}
  </div>;
}

// ═══ FORMS ═══
function SyncForm({onSync,onCancel,saving,syncStatus}){const[url,setUrl]=useState(localStorage.getItem("wauya_leads_folder")||"");return<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{background:C.bg,borderRadius:10,padding:14,border:`1px solid ${C.b}`,fontSize:12,color:C.tm,lineHeight:1.7}}>Pega el link de tu carpeta <strong style={{color:C.acc}}>leads entrantes</strong>. Cada subcarpeta = un prospecto.</div><Inp label="Link de carpeta" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://drive.google.com/drive/folders/..."/>{syncStatus&&<div style={{fontSize:12,color:C.acc}}>{syncStatus}</div>}<div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onCancel} v="ghost">Cancelar</Btn><Btn onClick={()=>onSync(url)} disabled={!url||saving} icon="sync">{saving?"...":"Sincronizar"}</Btn></div></div>}

// ─── UNIVERSAL TASK FORM ───
function FTGlobal({clients,prospects,emps,onDone,onX,init,isEdit,defaults={}}){
  const[f,s]=useState(init?{title:init.title||"",description:init.description||"",priority:init.priority||"media",status:init.status||"pendiente",assigned_to:init.assigned_to||"",start_date:init.start_date||todayStr(),end_date:init.end_date||"",category:init.category||"cliente",client_id:init.client_id||"",prospect_id:init.prospect_id||"",url:init.url||"",project_type:init.project_type||""}:{title:"",description:"",priority:defaults.priority||"alta",status:"pendiente",assigned_to:"",start_date:todayStr(),end_date:"",category:defaults.category||"cliente",client_id:defaults.client_id||"",prospect_id:defaults.prospect_id||"",url:"",project_type:""});

  return<div style={{display:"flex",flexDirection:"column",gap:14}}>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
      <Sel label="Categoría" value={f.category} onChange={e=>s({...f,category:e.target.value,client_id:e.target.value!=="cliente"?null:f.client_id,prospect_id:e.target.value!=="propuesta"?null:f.prospect_id})} options={CATS}/>
      <Sel label="Tipo de proyecto" value={f.project_type} onChange={e=>s({...f,project_type:e.target.value})} options={PROJ_TYPES}/>
    </div>
    {f.category==="cliente"&&<Sel label="Cliente" value={f.client_id||""} onChange={e=>s({...f,client_id:e.target.value||null})} options={[{value:"",label:"— Seleccionar —"},...clients.map(c=>({value:c.id,label:c.company||c.name}))]}/>}
    {f.category==="propuesta"&&<Sel label="Prospecto" value={f.prospect_id||""} onChange={e=>s({...f,prospect_id:e.target.value||null})} options={[{value:"",label:"— Seleccionar —"},...prospects.map(p=>({value:p.id,label:p.company||p.name}))]}/>}
    <Inp label="Título de la tarea" value={f.title} onChange={e=>s({...f,title:e.target.value})} placeholder="Diseñar propuesta visual, crear catálogo..."/>
    <Txt label="Detalles" value={f.description} onChange={e=>s({...f,description:e.target.value})} placeholder="Descripción del trabajo..."/>
    <Inp label="URL de referencia (Drive, Canva, web)" value={f.url} onChange={e=>s({...f,url:e.target.value})} placeholder="https://..."/>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
      <Sel label="Prioridad" value={f.priority} onChange={e=>s({...f,priority:e.target.value})} options={PRIOS}/>
      <Sel label="Estado" value={f.status} onChange={e=>s({...f,status:e.target.value})} options={TSTAT}/>
    </div>
    <Sel label="Asignar a" value={f.assigned_to||""} onChange={e=>s({...f,assigned_to:e.target.value||null})} options={[{value:"",label:"Sin asignar"},...emps.map(e=>({value:e.id,label:e.name}))]}/>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
      <Inp label="Inicio" type="date" value={f.start_date||""} onChange={e=>s({...f,start_date:e.target.value})}/>
      <Inp label="Entrega" type="date" value={f.end_date||""} onChange={e=>s({...f,end_date:e.target.value})}/>
    </div>
    <div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.title)onDone(f)}} disabled={!f.title}>{isEdit?"Guardar":"Crear"}</Btn></div>
  </div>;
}

function FP({onDone,onX}){const[f,s]=useState({name:"",company:"",email:"",phone:"",services:""});return<div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={f.name} onChange={e=>s({...f,name:e.target.value})}/><Inp label="Empresa" value={f.company} onChange={e=>s({...f,company:e.target.value})}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Inp label="Email" type="email" value={f.email} onChange={e=>s({...f,email:e.target.value})}/><Inp label="Teléfono" value={f.phone} onChange={e=>s({...f,phone:e.target.value})}/></div><Inp label="Servicios" value={f.services} onChange={e=>s({...f,services:e.target.value})}/><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.name)onDone(f)}} disabled={!f.name}>Crear</Btn></div></div>}
function FC({onDone,onX}){const[f,s]=useState({name:"",company:"",email:"",phone:"",services:"",notes:""});return<div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={f.name} onChange={e=>s({...f,name:e.target.value})}/><Inp label="Empresa" value={f.company} onChange={e=>s({...f,company:e.target.value})}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Inp label="Email" type="email" value={f.email} onChange={e=>s({...f,email:e.target.value})}/><Inp label="Teléfono" value={f.phone} onChange={e=>s({...f,phone:e.target.value})}/></div><Inp label="Servicios" value={f.services} onChange={e=>s({...f,services:e.target.value})}/><Txt label="Notas" value={f.notes} onChange={e=>s({...f,notes:e.target.value})}/><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.name)onDone(f)}} disabled={!f.name}>Crear</Btn></div></div>}
function FCU({onDone,onX}){const[f,s]=useState({name:"",email:"",password:""});const gen=()=>{let p="";for(let i=0;i<8;i++)p+="abcdefghijkmnpqrstuvwxyz23456789"[Math.floor(Math.random()*31)];s({...f,password:p})};return<div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={f.name} onChange={e=>s({...f,name:e.target.value})}/><Inp label="Email" type="email" value={f.email} onChange={e=>s({...f,email:e.target.value})}/><div><Inp label="Contraseña" value={f.password} onChange={e=>s({...f,password:e.target.value})}/><button onClick={gen} style={{background:"none",border:"none",color:C.acc,fontSize:10,cursor:"pointer",fontFamily:F,marginTop:4}}>Generar</button></div><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.name&&f.email&&f.password)onDone(f)}} disabled={!f.name||!f.email||!f.password}>Crear</Btn></div></div>}
function FE({onDone,onX}){const[f,s]=useState({name:"",email:"",password:"",role:""});const gen=()=>{let p="";for(let i=0;i<8;i++)p+="abcdefghijkmnpqrstuvwxyz23456789"[Math.floor(Math.random()*31)];s({...f,password:p})};return<div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={f.name} onChange={e=>s({...f,name:e.target.value})}/><Inp label="Cargo" value={f.role} onChange={e=>s({...f,role:e.target.value})}/><Inp label="Email" type="email" value={f.email} onChange={e=>s({...f,email:e.target.value})}/><div><Inp label="Contraseña" value={f.password} onChange={e=>s({...f,password:e.target.value})}/><button onClick={gen} style={{background:"none",border:"none",color:C.acc,fontSize:10,cursor:"pointer",fontFamily:F,marginTop:4}}>Generar</button></div><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.name&&f.email&&f.password)onDone(f)}} disabled={!f.name||!f.email||!f.password}>Crear</Btn></div></div>}
function FU({types,onDone,onX}){const[tp,sTp]=useState(types[0].value);const[sel,sSel]=useState(null);const ref=useRef(null);return<div style={{display:"flex",flexDirection:"column",gap:14}}><Sel label="Tipo" value={tp} onChange={e=>sTp(e.target.value)} options={types}/><div onClick={()=>ref.current?.click()} style={{border:`2px dashed ${C.b}`,borderRadius:12,padding:28,textAlign:"center",cursor:"pointer"}}><input ref={ref} type="file" style={{display:"none"}} onChange={e=>{if(e.target.files[0])sSel(e.target.files[0])}}/>{sel?<div style={{fontSize:12,color:C.tx}}>📎 {sel.name}</div>:<div><div style={{fontSize:24,marginBottom:6}}>📁</div><div style={{fontSize:12,color:C.tm}}>Click para seleccionar</div></div>}</div><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(sel)onDone(sel,tp)}} disabled={!sel}>Subir</Btn></div></div>}
function FEditUser({user:u,table,onDone,onX}){const[f,s]=useState({name:u.name||"",email:u.email||"",password:u.password||""});const[showPw,setShowPw]=useState(false);const gen=()=>{let p="";for(let i=0;i<8;i++)p+="abcdefghijkmnpqrstuvwxyz23456789"[Math.floor(Math.random()*31)];s({...f,password:p})};return<div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={f.name} onChange={e=>s({...f,name:e.target.value})}/><Inp label="Email" type="email" value={f.email} onChange={e=>s({...f,email:e.target.value})}/><div><Inp label="Contraseña" type={showPw?"text":"password"} value={f.password} onChange={e=>s({...f,password:e.target.value})}/><div style={{display:"flex",gap:12,marginTop:4}}><button onClick={()=>setShowPw(!showPw)} style={{background:"none",border:"none",color:C.tm,fontSize:10,cursor:"pointer",fontFamily:F}}>{showPw?"🙈":"👁️"}</button><button onClick={gen} style={{background:"none",border:"none",color:C.acc,fontSize:10,cursor:"pointer",fontFamily:F}}>🔄 Generar</button></div></div><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Btn onClick={onX} v="ghost">Cancelar</Btn><Btn onClick={()=>{if(f.name&&f.email&&f.password)onDone(f)}} disabled={!f.name||!f.email||!f.password}>Guardar</Btn></div></div>}
function SettingsView({user:u,onSave,onBack}){const[name,setName]=useState(u?.name||"");const[email,setEmail]=useState(u?.email||"");const[curPw,setCurPw]=useState("");const[newPw,setNewPw]=useState("");const[confirmPw,setConfirmPw]=useState("");const[showPw,setShowPw]=useState(false);const[msg,setMsg]=useState("");const[err,setErr]=useState("");const handleSave=async()=>{setErr("");setMsg("");const{data}=await supabase.from("admin_users").select("password").eq("id",u.id).single();if(!data||data.password!==curPw){setErr("Contraseña incorrecta");return}const upd={name,email};if(newPw){if(newPw.length<4){setErr("Mínimo 4 caracteres");return}if(newPw!==confirmPw){setErr("No coinciden");return}upd.password=newPw}await onSave(upd);setCurPw("");setNewPw("");setConfirmPw("");setMsg("Actualizado")};return<div><button onClick={onBack} style={{display:"flex",alignItems:"center",gap:5,background:"none",border:"none",color:C.tm,cursor:"pointer",fontSize:12,marginBottom:18,padding:0,fontFamily:F}}><Ic n="back" sz={15}/>Volver</button><h1 style={{fontFamily:D,fontSize:24,fontWeight:700,color:C.tx,marginBottom:24}}>Configuración</h1><Card style={{marginBottom:20,maxWidth:500}}><h3 style={{fontFamily:D,fontSize:14,fontWeight:600,color:C.tx,marginBottom:16}}>Cuenta</h3><div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Nombre" value={name} onChange={e=>setName(e.target.value)}/><Inp label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div></Card><Card style={{marginBottom:20,maxWidth:500}}><h3 style={{fontFamily:D,fontSize:14,fontWeight:600,color:C.tx,marginBottom:16}}>Contraseña</h3><div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Actual" type={showPw?"text":"password"} value={curPw} onChange={e=>setCurPw(e.target.value)}/><Inp label="Nueva" type={showPw?"text":"password"} value={newPw} onChange={e=>setNewPw(e.target.value)}/><Inp label="Confirmar" type={showPw?"text":"password"} value={confirmPw} onChange={e=>setConfirmPw(e.target.value)}/><button onClick={()=>setShowPw(!showPw)} style={{background:"none",border:"none",color:C.tm,fontSize:11,cursor:"pointer",fontFamily:F,textAlign:"left",padding:0}}>{showPw?"🙈 Ocultar":"👁️ Mostrar"}</button></div></Card>{err&&<div style={{color:C.r,fontSize:12,marginBottom:12}}>❌ {err}</div>}{msg&&<div style={{color:C.g,fontSize:12,marginBottom:12}}>✅ {msg}</div>}<Btn onClick={handleSave} disabled={!curPw||!name||!email} sz="lg">Guardar</Btn></div>}
